### ISSUE TITLE
Extrahieren von Puzzleteilen 

### ISSUE THREAD

**Issue by HippoDaPotato** [byWulf/jigsawlutioner#10]
Puzzleteile werden von Scan losgelöst und vereinzelt.

**Comment by byWulf** [comment]
Hello and welcome to Github!

Please provide more information when submitting an issue:
* What is the exact problem?
* What is the expected result?
* How can the issue be reproduced? Do you have example pieces?

**Comment by HippoDaPotato** [comment]
Apologies I am being taught how git works and I made a mistake opening several projects. I really did not mean to !  I do not know how to delete my mistake though .

**Comment by byWulf** [comment]
No problem, everyone starts at some point! I guess only project admins can permanently delete issues. But you can always close them. I will do it for you, so no worries :)
